shfSecurity:
  index:
    security: false
  login:
    security: false
  logout:
    security: true
  noPermission:
    security: false

default:
  index:
    security: true
    credentials:
      - admin
  insert:
    security: true
